FROM ubuntu:24.04

# Ustawienia środowiska i aktualizacja
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    curl \
    wget \
    unzip \
    zip \
    git \
    software-properties-common \
    python3.10 \
    python3-pip \
    openjdk-8-jdk \
    && rm -rf /var/lib/apt/lists/*

# Ustawienie JAVA_HOME
ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
ENV PATH=$JAVA_HOME/bin:$PATH

# Instalacja Kotlin
RUN curl -s https://get.sdkman.io | bash && \
    bash -c "source $HOME/.sdkman/bin/sdkman-init.sh && sdk install kotlin"

# Instalacja Gradle
ENV GRADLE_VERSION=8.7
RUN wget https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip -P /tmp && \
    unzip -d /opt/gradle /tmp/gradle-${GRADLE_VERSION}-bin.zip && \
    ln -s /opt/gradle/gradle-${GRADLE_VERSION}/bin/gradle /usr/bin/gradle

# Utwórz katalog na projekt
WORKDIR /app

# Kopiowanie plików projektu
COPY . .

# Budowanie projektu
RUN gradle build

# Domyślne uruchomienie
CMD ["gradle", "run"]
